#!/bin/bash

# make sure we are in the same directory as the script.
DIR=$( cd "$( dirname "$0" )" && pwd )
cd $DIR

# get configuration
source ./config

# script must be run as root
if [[ $EUID -ne 0 ]]; then
echo "This script must be run as root" 1>&2
   exit 1
fi

# copy built configs
echo "copying built configs to /"
mv ./build/* /

# remove build directory
echo "removing build directory"
rmdir ./build

# install emacs
echo "installing emacs"
aptitude install emacs

# install necessary gconf
echo "installing gconf"
aptitude install gconf-defaults-service

# install necessary component for kane's emacs color themes
echo "installing color themes"
aptitude install emacs-goodies-el

# install open jdk
echo "installing openjdk"
aptitude install openjdk-6-jdk

# get leiningen
echo "installing leiningen"
wget https://raw.github.com/technomancy/leiningen/stable/bin/lein

# make sure ~/bin exists, create if not
if [ ! -e ~/bin]
then
    mkdir ~/bin
fi

# move install file to ~/bin, set executable, execute
mv lein ~/bin
chmod 755 ~/bin/lein